apiVersion: apps/v1
kind: Deployment
metadata:
  name:  devops-kubernetes-traning-web
  namespace: default
  labels:
    app:  devops-kubernetes-traning-web 
spec:
  selector:
    matchLabels:
      app: devops-kubernetes-traning-web
  replicas: 1
  template:
    metadata:
      labels:
        app:  devops-kubernetes-traning-web
    spec:
      containers:
      - name:  devops-kubernetes-traning-web
        image: appstellar/devops-kubernetes-training-web
        resources:
          requests:
            cpu: 1000m
            memory: 2000Mi
          limits:
            cpu: 1000m
            memory: 2000Mi
        ports:
        - containerPort: 3000